
package sageapp.view;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.Collections;
import java.util.Comparator;

//import java.awt.Dimension;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.JButton;
//import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import sageapp.DAO.BillDAO;
import sageapp.model.AuthData;
import sageapp.DAO.ProductDAO;
import sageapp.model.BillData;
import sageapp.model.BillModel;
import sageapp.model.ProductData;
//import sageapp.model.ProductModel;

/**
 *
 * @author sangyakoirala
 */
 final class HistoryView extends javax.swing.JFrame {
     AuthData user;
     int uid;  
     BillDAO billDAO;

     List<BillData> billData;
    /**
     * Creates new form Login
     */
    public HistoryView(AuthData user) {
        this.billDAO = new BillDAO();
        this.user = user;
        this.uid=user.getUid();
        this.billData= billDAO.fetchAllBillsByUid(uid);
     
        // Sort the bills by date_of_creation (Timestamp)
        Collections.sort(billData, (BillData bill1, BillData bill2) -> bill2.getDateOfCreation().compareTo(bill1.getDateOfCreation()));
        System.out.println("Bills::"+billData);  
        initComponents();
        
        uI();
        setSize(700, 400);
        setResizable(false); 
        setLocationRelativeTo(null);
    }
       void uI(){
        setTitle("Add Product View");
        setResizable(false);
        setLayout(new BorderLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setBounds(250, 10, 489, 650);
        setBackground(Color.decode(("#EBEBEB")));
//        logoutButton =  new javax.swing.JButton();
//        logoutButton.setBounds(1,1,100,100);
//        logoutButton.setIcon(icon1);
//        logoutButton.setBackground(Color.WHITE);
//        add(logoutButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        popupMenu1 = new java.awt.PopupMenu();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addProductButton = new javax.swing.JButton();
        viewProductButton = new javax.swing.JButton();
        billingButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        logoutButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setMinimumSize(new java.awt.Dimension(0, 0));
        jTable3.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane4.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/logo1.png"))); // NOI18N

        addProductButton.setText("Add Product");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        viewProductButton.setText("View Product");
        viewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductButtonActionPerformed(evt);
            }
        });

        billingButton.setText("Billing");
        billingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingButtonActionPerformed(evt);
            }
        });

        historyButton.setText("History");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleLabel.setBackground(new java.awt.Color(0, 153, 153));
        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 102));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("History of Bills");

        DefaultTableModel model = new DefaultTableModel(
            new String[]{"S.N.", "Bill Number", "Customer Name", "Total Price"}, 0
        ) {
            Class[] types = new Class[]{
                Integer.class, String.class, Double.class, Integer.class, Object.class
            };

            boolean[] canEdit = new boolean[]{false, false, false, false, true};

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        if (billData != null) {
            int sn = 1;
            for (BillData bill : billData) {
                //        JButton editButton = new JButton("Edit");
                //        editButton.addActionListener(evt -> editProductAction(product));  // Action for edit button
                //
                //        JButton deleteButton = new JButton("Delete");
                //        deleteButton.addActionListener(evt -> deleteProductAction(product));  // Action for delete button

                model.addRow(new Object[]{
                    sn++,
                    bill.getBillId(),
                    bill.getName(),
                    bill.getTotalPrice(),

                });
            }
        }
        productsTable.setModel(model
        );
        // Center-align the text in all columns
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < productsTable.getColumnCount(); i++) {
            productsTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        productsTable.setPreferredSize(new java.awt.Dimension(700, 400));
        productsTable.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                int row = productsTable.getSelectedRow();
                if (row != -1) {
                    // Get the product object from the selected row
                    BillData bill = billData.get(row);
                    // Call a method to pass the selected product
                    billRowClicked(bill);
                }
            }
        });
        jScrollPane5.setViewportView(productsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/logoutIcon.png"))); // NOI18N
        logoutButton.setIconTextGap(0);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/profileIcon.png"))); // NOI18N
        profileButton.setIconTextGap(0);
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(addProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(billingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(historyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(historyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void editProductAction(ProductData product){
    
}
private void deleteProductAction(ProductData product){
    
}
    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
    AddProductView addProductView = new AddProductView(user);
    addProductView.setSize(700, 400);
    addProductView.setLocationRelativeTo(null);
    addProductView.setVisible(true);
    this.dispose();  
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
     int response = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to log out?", 
        "Logout Confirmation", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE
    );

    if (response != JOptionPane.YES_OPTION) {
        return; // Exit the method without logging out if the user selects "No"
    }

    LoginView loginView = new LoginView();
    loginView.setSize(700, 400);
    loginView.setLocationRelativeTo(null);
    loginView.setVisible(true);
    this.dispose();  // Close the current window
        
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
    ProfileView productView;
         try {
             productView = new ProfileView(uid);
             
    productView.setSize(700, 400);
    productView.setLocationRelativeTo(null);
    productView.setVisible(true);
         } catch (IOException ex) {
             Logger.getLogger(AddProductView.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_profileButtonActionPerformed

    private void billingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingButtonActionPerformed
        // TODO add your handling code here:
        BillingView bv= new BillingView(user);
        bv.setSize(700,400);
        bv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_billingButtonActionPerformed

    private void viewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductButtonActionPerformed
        // TODO add your handling code here:
    ViewProducts   productView = new ViewProducts(user);         
    productView.setSize(700, 400);
    productView.setLocationRelativeTo(null);
    productView.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_viewProductButtonActionPerformed


private void billRowClicked(BillData bill) {
    printBill(bill);
//    showProductDetails(product);
}
private void printBill(BillData bill) {
    // Fetch customer details from the UI
    String customerName = bill.getName();
    String customerNumber = bill.getPhone();

    // Start building the bill details
    StringBuilder billDetails = new StringBuilder();
    billDetails.append("Customer Name: ").append(customerName).append("\n");
    billDetails.append("Customer Phone: ").append(customerNumber).append("\n\n");
    billDetails.append("---------------------------------------------------------\n");
    billDetails.append("Product Name\t\tPrice\tQuantity\tTotal\n");
    billDetails.append("---------------------------------------------------------\n");

    // Variable to store the total price of the bill
    double totalBillPrice = 0.0;

    // Loop through the products in the bill and display them
    for (Map.Entry<ProductData, Integer> entry : bill.getProductQuantityMap().entrySet()) {
        ProductData product = entry.getKey();
        Integer quantity = entry.getValue();
        
        // Get product details (name and price) from ProductData object
        String productName = product.getName();
        double productPrice = product.getPrice();
        
        // Calculate the total price for this product (price * quantity)
        double productTotalPrice = productPrice * quantity;
        
        // Add this product's details to the bill details
        billDetails.append(String.format("%-18s\t%.2f\t%d\t\t%.2f\n", productName, productPrice, quantity, productTotalPrice));
        
        // Add the product total price to the overall bill total
        totalBillPrice += productTotalPrice;
    }

    // Add total price at the bottom
    billDetails.append("---------------------------------------------------------\n")
               .append("Total Price: $").append(String.format("%.2f", totalBillPrice)).append("\n");

    // Create a JTextArea to display the bill details
    JTextArea textArea = new JTextArea(billDetails.toString());
    textArea.setEditable(false); // Make the text area non-editable
    textArea.setLineWrap(true);
    textArea.setWrapStyleWord(true);
    
    // Increase the font size for better readability
    textArea.setFont(new Font("Monospaced", Font.PLAIN, 14));

    // Create a JScrollPane to allow scrolling if the content overflows
    JScrollPane scrollPane = new JScrollPane(textArea);
    scrollPane.setPreferredSize(new Dimension(500, 300)); // Set a larger preferred size for the scroll pane

    // Show the bill details in a dialog box with a larger size
    JOptionPane.showMessageDialog(
        null,
        scrollPane,
        "Bill Details",
        JOptionPane.INFORMATION_MESSAGE
    );
}
private void showProductDetails(ProductData product) {
    // Example code to display product details (e.g., in a new window or dialog)
    JOptionPane.showMessageDialog(null, "Product UID: " + product.getUid()+ "\nID: " + product.getId()+ "\nName: " + product.getName() + "\nPrice: " + product.getPrice() + "\nStock: " + product.getStock());
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddProductView(user).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddProductView(user).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddProductView(user).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddProductView(user).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton billingButton;
    private javax.swing.JButton historyButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton logoutButton;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable productsTable;
    private javax.swing.JButton profileButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewProductButton;
    // End of variables declaration//GEN-END:variables

 }
