
package sageapp.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;
import sageapp.DAO.AuthDAO;
import sageapp.model.AuthData;
import sageapp.DAO.ProductDAO;
import sageapp.model.ProductModel;
import sageapp.model.UpdatePasswordModel;
import sageapp.model.UpdateProfileModel;
import sageapp.model.UpdateProfilePictureModel;

/**
 *
 * @author sangyakoirala
 */
 final class PasswordChangeView extends javax.swing.JFrame {
     AuthData user;
     int uid;
     String fName;
     String lName;
     String email;
     String password;
     byte[] image;
     String img;
     ImageIcon profileIcon ;
     boolean visibility=false;     
     boolean nvisibility=false;
     boolean confirmvisibility=false;


     
     
    /**
     * Creates new form Login
     */
    public PasswordChangeView(int uid) throws IOException {
         this.uid=uid;
        System.out.println("uid Profile VIEW"+uid);
        AuthDAO auth= new AuthDAO();
        this.user=auth.getUser(uid);
        this.fName=user.getFname();
        this.email=user.getEmail();
        this.lName=user.getLname();
        this.image=user.getImage();
        this.password= user.getPassword();
   ByteArrayInputStream bis = new ByteArrayInputStream(image);
        java.awt.Image img = ImageIO.read(bis);
        img = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH); 
     this.profileIcon= new ImageIcon(img);
        System.out.println("USER Profile VIEW"+user.getFname());
        initComponents();
       
        uI();
        setSize(700, 400);
        setResizable(false); 
        setLocationRelativeTo(null);
    }
       void uI(){
        setTitle("Add Product View");
        setResizable(false);
        setLayout(new BorderLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setBounds(250, 10, 489, 650);
        setBackground(Color.decode(("#EBEBEB")));
        ImageIcon icon1 = new ImageIcon("Public\\logo.png");
//        logoutButton =  new javax.swing.JButton();
//        logoutButton.setBounds(1,1,100,100);
//        logoutButton.setIcon(icon1);
//        logoutButton.setBackground(Color.WHITE);
//        add(logoutButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        popupMenu1 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        billingButton = new javax.swing.JButton();
        changeDetailsButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        changePasswordButton = new javax.swing.JButton();
        noAccountLabel = new javax.swing.JLabel();
        noAccountLabel4 = new javax.swing.JLabel();
        noAccountLabel5 = new javax.swing.JLabel();
        currentPasswordTextField = new javax.swing.JPasswordField();
        newPasswordTextField = new javax.swing.JPasswordField();
        confirmPasswordTextField = new javax.swing.JPasswordField();
        visibilityButton = new javax.swing.JButton();
        visibilityButton1 = new javax.swing.JButton();
        visibilityButton2 = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        titleLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/logo1.png"))); // NOI18N

        billingButton.setText("Change Picture");
        billingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingButtonActionPerformed(evt);
            }
        });

        changeDetailsButton.setText("Change Details");
        changeDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDetailsButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleLabel.setBackground(new java.awt.Color(0, 153, 153));
        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 102));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Change Password");

        changePasswordButton.setBackground(new java.awt.Color(0, 102, 102));
        changePasswordButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        changePasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        changePasswordButton.setText("Change Password");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        noAccountLabel.setBackground(new java.awt.Color(0, 153, 153));
        noAccountLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        noAccountLabel.setForeground(new java.awt.Color(51, 51, 51));
        noAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noAccountLabel.setText("Current Password");

        noAccountLabel4.setBackground(new java.awt.Color(0, 153, 153));
        noAccountLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        noAccountLabel4.setForeground(new java.awt.Color(51, 51, 51));
        noAccountLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noAccountLabel4.setText("New Password");

        noAccountLabel5.setBackground(new java.awt.Color(0, 153, 153));
        noAccountLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        noAccountLabel5.setForeground(new java.awt.Color(51, 51, 51));
        noAccountLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noAccountLabel5.setText("Confirm Password");

        visibilityButton.setText("Show");
        visibilityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibilityButtonActionPerformed(evt);
            }
        });

        visibilityButton1.setText("Show");
        visibilityButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibilityButton1ActionPerformed(evt);
            }
        });

        visibilityButton2.setText("Show");
        visibilityButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibilityButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(noAccountLabel4)
                                .addComponent(noAccountLabel))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titleLabel)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(currentPasswordTextField)
                                    .addComponent(newPasswordTextField)
                                    .addComponent(confirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(noAccountLabel5))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visibilityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visibilityButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visibilityButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleLabel)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noAccountLabel)
                    .addComponent(currentPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visibilityButton))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noAccountLabel4)
                    .addComponent(newPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visibilityButton1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noAccountLabel5)
                    .addComponent(confirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visibilityButton2))
                .addGap(18, 18, 18)
                .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/logoutIcon.png"))); // NOI18N
        logoutButton.setIconTextGap(0);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        titleLabel1.setBackground(new java.awt.Color(0, 153, 153));
        titleLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel1.setForeground(new java.awt.Color(0, 102, 102));
        titleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel1.setIcon(profileIcon);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/backIcon.png"))); // NOI18N
        backButton.setIconTextGap(0);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(changeDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(billingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
     int response = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to log out?", 
        "Logout Confirmation", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE
    );

    if (response != JOptionPane.YES_OPTION) {
        return; // Exit the method without logging out if the user selects "No"
    }

    LoginView loginView = new LoginView();
    loginView.setSize(700, 400);
    loginView.setLocationRelativeTo(null);
    loginView.setVisible(true);
    this.dispose();  // Close the current window
        
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
         this.dispose(); 
    }//GEN-LAST:event_backButtonActionPerformed

    private void billingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingButtonActionPerformed
        // TODO add your handling code here:
     JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Select Profile Picture");
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "jpeg", "png"));

    int returnValue = fileChooser.showOpenDialog(null);
    
    if (returnValue == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        
        try {
            BufferedImage originalImage = ImageIO.read(selectedFile);
            if (originalImage != null) {
                // Scale the image properly
                BufferedImage resizedImage = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);
                Graphics2D g2d = resizedImage.createGraphics();
                g2d.drawImage(originalImage, 0, 0, 100, 100, null);
                g2d.dispose();
                
                // Set the resized image as profile icon
                ImageIcon profileIcon1 = new ImageIcon(resizedImage);
                titleLabel1.setIcon(profileIcon1);
                
                // Convert image to byte array (if needed for database storage)
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(resizedImage, "png", baos);
                image = baos.toByteArray();
                 UpdateProfilePictureModel pm = new UpdateProfilePictureModel(uid,image);
                  AuthDAO auth = new AuthDAO();
                    AuthData userm;
                try {
             userm = auth.updateProfilePicture(pm,uid);
              this.user=userm;
         } catch (SQLException ex) {
             Logger.getLogger(PasswordChangeView.class.getName()).log(Level.SEVERE, null, ex);
         }                 
                System.out.println("Profile picture updated successfully.");
            } else {
                System.out.println("Invalid image file.");
            }
        } catch (IOException ex) {
            System.out.println("Error loading image: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_billingButtonActionPerformed

    private void changeDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDetailsButtonActionPerformed
         try {
             // TODO add your handling code here:
             ProfileView pv= new ProfileView(uid);
             pv.setVisible(true);
             this.dispose();
         } catch (IOException ex) {
             Logger.getLogger(PasswordChangeView.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_changeDetailsButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed

        // TODO add your handling code here:
        String currentPassword=currentPasswordTextField.getText();
        String newPassword=newPasswordTextField.getText();
        String confirmPassword= confirmPasswordTextField.getText();
        if(currentPassword.isEmpty() || "".equals(currentPassword)||newPassword.isEmpty() || "".equals(newPassword)||confirmPassword.isEmpty() || "".equals(confirmPassword)){
            JOptionPane.showMessageDialog(this, "Please enter all the fields");
            return;
        }
        if (currentPassword.equals(this.password)){
            if(newPassword.equals(confirmPassword)){
                AuthDAO auth= new AuthDAO();
                UpdatePasswordModel profile = new UpdatePasswordModel(uid,newPassword); 
                try {
                    auth.updatePassword(profile, uid);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(PasswordChangeView.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }else{
                 JOptionPane.showMessageDialog(this, "New Password and Confirm Password do not match");
            return;
            }
        } else{
            JOptionPane.showMessageDialog(this, "Current Password is not correct");
            return;
        }
       
        UpdatePasswordModel lm = new UpdatePasswordModel(uid,newPassword);
        AuthDAO auth = new AuthDAO();
        AuthData userm;
         try {
             userm = auth.updatePassword(lm,uid);
                     this.user=userm;
                     

        JOptionPane.showMessageDialog(this, "Profile Updated Successfully");
         } catch (SQLException ex) {
             Logger.getLogger(PasswordChangeView.class.getName()).log(Level.SEVERE, null, ex);
         }


    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void visibilityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibilityButtonActionPerformed
        // TODO add your handling code here:
        this.visibility = !visibility;
        if (this.visibility) {
        visibilityButton.setText("Hide");
        currentPasswordTextField.setEchoChar((char) 0); // Show text (no masking)
    } else {
        visibilityButton.setText("Show");
        currentPasswordTextField.setEchoChar('*'); // Hide text (mask input)
    }
    }//GEN-LAST:event_visibilityButtonActionPerformed

    private void visibilityButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibilityButton1ActionPerformed
        // TODO add your handling code here:
           // TODO add your handling code here:
        this.nvisibility = !nvisibility;
        if (this.nvisibility) {
        visibilityButton1.setText("Hide");
        newPasswordTextField.setEchoChar((char) 0); // Show text (no masking)
    } else {
        visibilityButton1.setText("Show");
        newPasswordTextField.setEchoChar('*'); // Hide text (mask input)
    }
    }//GEN-LAST:event_visibilityButton1ActionPerformed

    private void visibilityButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibilityButton2ActionPerformed
        // TODO add your handling code here:
        this.confirmvisibility = !confirmvisibility;
        if (this.confirmvisibility) {
        visibilityButton2.setText("Hide");
        confirmPasswordTextField.setEchoChar((char) 0); // Show text (no masking)
    } else {
        visibilityButton2.setText("Show");
        confirmPasswordTextField.setEchoChar('*'); // Hide text (mask input)
    }
    }//GEN-LAST:event_visibilityButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordChangeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddProductView(user).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddProductView(user).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddProductView(user).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddProductView(user).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton billingButton;
    private javax.swing.JButton changeDetailsButton;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JPasswordField confirmPasswordTextField;
    private javax.swing.JPasswordField currentPasswordTextField;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPasswordField newPasswordTextField;
    private javax.swing.JLabel noAccountLabel;
    private javax.swing.JLabel noAccountLabel4;
    private javax.swing.JLabel noAccountLabel5;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JButton visibilityButton;
    private javax.swing.JButton visibilityButton1;
    private javax.swing.JButton visibilityButton2;
    // End of variables declaration//GEN-END:variables

 }
