
package sageapp.view;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

//import java.awt.Dimension;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.JButton;
//import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import sageapp.model.AuthData;
import sageapp.DAO.ProductDAO;
import sageapp.model.ProductData;
//import sageapp.model.ProductModel;

/**
 *
 * @author sangyakoirala
 */
 final class ViewProducts extends javax.swing.JFrame {
     AuthData user;
     int uid;  
     ProductDAO productDAO;
     List<ProductData> products;
    /**
     * Creates new form Login
     */
    public ViewProducts(AuthData user) {
    
        this.productDAO = new ProductDAO();
        this.user = user;
        this.products=productDAO.viewAllProducts(user.getUid());
        System.out.println("Products::"+products);

        this.uid=user.getUid();
        System.out.println("uid "+uid);    
        initComponents();
        
        uI();
        setSize(700, 400);
        setResizable(false); 
        setLocationRelativeTo(null);
    }
       void uI(){
        setTitle("Add Product View");
        setResizable(false);
        setLayout(new BorderLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setBounds(250, 10, 489, 650);
        setBackground(Color.decode(("#EBEBEB")));
//        logoutButton =  new javax.swing.JButton();
//        logoutButton.setBounds(1,1,100,100);
//        logoutButton.setIcon(icon1);
//        logoutButton.setBackground(Color.WHITE);
//        add(logoutButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        popupMenu1 = new java.awt.PopupMenu();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addProductButton = new javax.swing.JButton();
        viewProductButton = new javax.swing.JButton();
        billingButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        logoutButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setMinimumSize(new java.awt.Dimension(0, 0));
        jTable3.setPreferredSize(new java.awt.Dimension(700, 400));
        jScrollPane4.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/logo1.png"))); // NOI18N

        addProductButton.setText("Add Product");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        viewProductButton.setText("View Product");

        billingButton.setText("Billing");
        billingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingButtonActionPerformed(evt);
            }
        });

        historyButton.setText("History");
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleLabel.setBackground(new java.awt.Color(0, 153, 153));
        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 102));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("List of the Products");

        DefaultTableModel model = new DefaultTableModel(
            new String[]{"S.N.", "Name", "Price", "Stock"}, 0
        ) {
            Class[] types = new Class[]{
                Integer.class, String.class, Double.class, Integer.class, Object.class
            };

            boolean[] canEdit = new boolean[]{false, false, false, false, true};

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        // Fetch products and populate the table
        List<ProductData> products = productDAO.viewAllProducts(user.getUid());
        if (products != null) {
            int sn = 1;
            for (ProductData product : products) {
                JButton editButton = new JButton("Edit");
                editButton.addActionListener(evt -> editProductAction(product));  // Action for edit button

                JButton deleteButton = new JButton("Delete");
                deleteButton.addActionListener(evt -> deleteProductAction(product));  // Action for delete button

                model.addRow(new Object[]{
                    sn++,
                    product.getName(),
                    product.getPrice(),
                    product.getStock(),

                });
            }
        }
        productsTable.setModel(model
        );
        // Center-align the text in all columns
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < productsTable.getColumnCount(); i++) {
            productsTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        productsTable.setPreferredSize(new java.awt.Dimension(700, 400));
        productsTable.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                int row = productsTable.getSelectedRow();
                if (row != -1) {
                    // Get the product object from the selected row
                    ProductData product = products.get(row);
                    // Call a method to pass the selected product
                    productRowClicked(product);
                }
            }
        });
        jScrollPane5.setViewportView(productsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/logoutIcon.png"))); // NOI18N
        logoutButton.setIconTextGap(0);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/profileIcon.png"))); // NOI18N
        profileButton.setIconTextGap(0);
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(addProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(billingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(historyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(historyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void editProductAction(ProductData product){
    
}
private void deleteProductAction(ProductData product){
    
}
    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
    AddProductView addProductView = new AddProductView(user);
    addProductView.setSize(700, 400);
    addProductView.setLocationRelativeTo(null);
    addProductView.setVisible(true);
    this.dispose();  
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
     int response = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to log out?", 
        "Logout Confirmation", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE
    );

    if (response != JOptionPane.YES_OPTION) {
        return; // Exit the method without logging out if the user selects "No"
    }

    LoginView loginView = new LoginView();
    loginView.setSize(700, 400);
    loginView.setLocationRelativeTo(null);
    loginView.setVisible(true);
    this.dispose();  // Close the current window
        
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
    ProfileView productView;
         try {
             productView = new ProfileView(uid);
             
    productView.setSize(700, 400);
    productView.setLocationRelativeTo(null);
    productView.setVisible(true);
         } catch (IOException ex) {
             Logger.getLogger(AddProductView.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_profileButtonActionPerformed

    private void billingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingButtonActionPerformed
        // TODO add your handling code here:
        BillingView bv= new BillingView(user);
        bv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_billingButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        // TODO add your handling code here:
          HistoryView bv = new HistoryView(user);
        bv.setSize(700, 400);
        bv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_historyButtonActionPerformed
private void productRowClicked(ProductData product) {
    System.out.println("Product clicked: " + product.getName());
    
    showProductDetails(product);
}

private void showProductDetails(ProductData product) {
    // Create the main panel for product details
    JPanel mainPanel = new JPanel();
    mainPanel.setLayout(new FlowLayout(FlowLayout.LEADING));
    mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 3)); // Add padding around panel
    mainPanel.setAlignmentX(Component.LEFT_ALIGNMENT);

    // Create a panel for the table (product details in a table-like format)
    JPanel tablePanel = new JPanel();
    tablePanel.setLayout(new BoxLayout(tablePanel, BoxLayout.Y_AXIS)); // Vertical alignment of labels
    tablePanel.setAlignmentX(Component.LEFT_ALIGNMENT);

    // Create a 2D array for table data (each product attribute as a row)
    Object[][] tableData = {
        {"ID:", product.getId()},
        {"Name:", product.getName()},
        {"Description:", product.getDescription()},
        {"Price:", product.getPrice()},
        {"Stock:", product.getStock()}
    };

    // Column names
    String[] columnNames = {"Attribute", "Value"};

    // Create a JTable to display the product details in a table format
    JTable productTable = new JTable(tableData, columnNames) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };

    // Set the table to be non-editable
    productTable.setEnabled(false);

    // Set column widths for better readability
    productTable.getColumnModel().getColumn(0).setPreferredWidth(100);
    productTable.getColumnModel().getColumn(1).setPreferredWidth(250);

    // Enable text wrapping for the "Description" column (column 1)
    productTable.getColumnModel().getColumn(1).setCellRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            JTextArea textArea = new JTextArea();
            textArea.setText(value.toString());
            textArea.setWrapStyleWord(true);
            textArea.setLineWrap(true);
            textArea.setOpaque(false); // Make the background transparent
            textArea.setEditable(false);
            textArea.setFont(table.getFont());
            return textArea;
        }
    });

    // Set table appearance
    productTable.setFont(new Font("Arial", Font.PLAIN, 14));
    productTable.setRowHeight(35); // Increased row height for better visibility

    // Set custom table cell renderers for a nicer look
    productTable.setGridColor(Color.LIGHT_GRAY); // Set grid color for the table
    productTable.setShowGrid(true); // Show grid lines

    // Create a JScrollPane to make the table scrollable
    JScrollPane scrollPane = new JScrollPane(productTable);
    scrollPane.setPreferredSize(new Dimension(350, 205)); // Increase height of the table

    // Add the table (inside the scroll pane) to the table panel
    tablePanel.add(scrollPane);

    // Add the table panel to the main panel
    mainPanel.add(tablePanel);

    // Add some vertical space between table and buttons
    mainPanel.add(Box.createVerticalStrut(30));

    // Create a panel for buttons
    JPanel buttonPanel = new JPanel();
    buttonPanel.setLayout(new FlowLayout(FlowLayout.LEFT)); // Align the buttons to the left

    // Create Edit button
    JButton editButton = new JButton("Edit");
    editButton.setFont(new Font("Arial", Font.PLAIN, 12));
    editButton.setBackground(Color.BLUE);
    editButton.setForeground(Color.WHITE);
    editButton.setFocusPainted(false);
    editButton.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
    editButton.addActionListener(e -> editProduct(product));

    // Create Delete button
    JButton deleteButton = new JButton("Delete");
    deleteButton.setFont(new Font("Arial", Font.PLAIN, 12));
    deleteButton.setBackground(Color.RED);
    deleteButton.setForeground(Color.WHITE);
    deleteButton.setFocusPainted(false);
    deleteButton.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
    deleteButton.addActionListener(e -> {
        // Show the delete confirmation dialog
        int result = JOptionPane.showConfirmDialog(mainPanel, 
                "Are you sure you want to delete this product?", 
                "Confirm Delete", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (result == JOptionPane.YES_OPTION) {
            deleteProduct(product, mainPanel); // Pass mainPanel to update after deletion
        }
    });

    // Add buttons to the button panel
    buttonPanel.add(editButton);
    buttonPanel.add(deleteButton);

    // Add the button panel to the main panel
    mainPanel.add(buttonPanel);

    // Add the main panel to the frame or container (instead of JDialog)
    JFrame frame = new JFrame("Product Details");
    frame.setSize(400, 400);
    frame.setLocationRelativeTo(null); // Center the window
    frame.add(mainPanel);
    frame.setVisible(true);
}


private void deleteProduct(ProductData product, JPanel mainPanel) {
    // Attempt to delete the product from the database
    boolean result = productDAO.deleteProductById(product.getId());

    if (result) {
        // Show a confirmation dialog indicating the product was deleted successfully
        JOptionPane.showMessageDialog(null, 
            "Product '" + product.getName() + "' has been successfully deleted.", 
            "Delete Successful", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Now directly update the products view (no JDialog involved)
        ViewProducts view = new ViewProducts(user);
        view.setSize(700, 400);  // Set the size for the ViewProducts window
        view.setVisible(true);   // Make the updated view visible

        // Optionally close the current window if it's no longer needed
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(mainPanel);
        parentFrame.dispose();  // Close the product details frame
        this.dispose();
    } else {
        // Show an error message if the deletion failed
        JOptionPane.showMessageDialog(null, 
            "Failed to delete the product.", 
            "Delete Failed", 
            JOptionPane.ERROR_MESSAGE);
    }
}

// Method to edit the product (implement as needed)
private void editProduct(ProductData product) {
    System.out.println("Editing product: " + product.getName());
    // Implement the logic to open an edit dialog and update the product
    EditProductView editProduct= new EditProductView(user,product);
    editProduct.setSize(700,400);
    editProduct.setVisible(true);
    this.dispose();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddProductView(user).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddProductView(user).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton billingButton;
    private javax.swing.JButton historyButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton logoutButton;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable productsTable;
    private javax.swing.JButton profileButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewProductButton;
    // End of variables declaration//GEN-END:variables

 }
